# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  apt_packages:
  - gettext
  tools:
    python: '3.11'

sphinx:
  configuration: conf.py
  # TODO: Re-enable failure on warnings when all translation issues are handled.
  # fail_on_warning: true

formats:
  - htmlzip
  - epub

python:
  install:
  - requirements: requirements.txt
