name: Translations update

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge-fast-forward:
    if: github.event.pull_request.user.login == 'zammad-sync'
    runs-on: ubuntu-latest
    steps:
      - name: Fast forward merge
        uses: sequoia-pgp/fast-forward@v1
        with:
          github_token: ${{ secrets.ZAMMAD_SYNC_PAT }}
          merge: true
          # To reduce the workflow's verbosity, we use 'on-error'
          #   to only post a comment when an error occurs.
          #   The information is still available in the step's summary.
          comment: on-error
          debug: true
